#import "../typst/general_math_commands.typ": *


#let Fanout = [$Omega$]
#let Fanin = [$Psi$]
#let fanout = [$omega$]
#let fanin = [$psi$]
#let dFanin = [$upright(d)Fanin$]
#let dFanout = [$upright(d)Fanout$]

#let covpostact = [$A$]
#let halfcov(s: "") = [$covpostact^(#s 1/2)$]

#let Layer(W: [W]) = [$upright(L)_(#W)$]
#let Lin = [$op("Lin")$]
#let Conv = [$op("Conv")$]
#let Linl(W: [W], c1: [c1], c2: [c2]) = [$op("Lin")^(#W)_(#c1, #c2)$]
#let Convl(W: [W], c1: [c1], c2: [c2]) = [$op("Conv")^(#W)_(#c1, #c2)$]
#let postact(l: []) = [$a_(#l)$]
#let preact(l: []) = [$s_(#l)$]
#let Postact(l: []) = [$bold(a)_(#l)$]
#let Preact(l: []) = [$bold(s)_(#l)$]

#let postactext = [$postact(l: -1)^("ext")$]
#let preactext = [$preact(l: -1)^("ext")$]
#let Postactext = [$Postact(l: -1)^("ext")$]
#let Preactext = [$Preact(l: -1)^("ext")$]

#let loss = [$cal(L)$]
#let gradpreact(l: []) = [$nabla_(preact(l: #l)) loss(f)$]


#let Gradpreact = [$nabla$]
#let dW = [$upright(d)W$]
#let dv = [$upright(d)v$]
#let DV = [$V$]
#let DE = [$hat(V)$]
#let dA = [$upright(d)A$]
#let deltaadd = [$delta_a$]
#let deltaupdate = [$delta_u$]
#let dtheta = [$upright(d)theta$]
#let da = [$upright(d)a$]
#let df = [$upright(d)f$]
#let cm = [$C_(-2)$]
#let cp = [$C$]
#let AlphaF = [$Alpha_F$]
#let OmegaF = [$Omega_F$]
#let datadist = [$cal(D)$]
#let Edata = [$EE_((x, y) ~ datadist)$]
#let orth(x) = [$#x^(bot)$]
#let orthp(x) = [$orth((#x))$]

#let deltas = [$delta_(preact())$]
#let Deltas = [$delta_(Preact())$]
#let cmid = [$C_(-1)$]
#let etasenn = [$eta_("SENN")$]
#let bottleneck = [$orthp(gradpreact())$]
#let Bottleneck = [$orth(Gradpreact)$]
#let cext = [$C_("ext")$]
#let covgrad = [$S$]
#let icovgrad = [$pinv(covgrad)$]
#let sqrtS = [$covgrad^(1/2)$]
#let isqrtS = [$covgrad^(-1/2)$]
#let sqrtA= [$covpostact_(-2)^(1/2)$]
#let isqrtA= [$covpostact_(-2)^(-1/2)$]
#let sqrtAext= [$(covpostact_(-1)^"ext")^(1/2)$]
#let isqrtAext= [$(covpostact_(-1)^"ext")^(-1/2)$]
